### ISSUE TITLE
rockopeaches Hacking

### ISSUE THREAD

**Issue by EtchedTree** [Year4000/Meta#14]
rockopeaches has been using fly to capture the wool very quickly.

Proof

![2015-04-02_11 34 49](https://cloud.githubusercontent.com/assets/11773605/6967377/e183561c-d92c-11e4-82ff-9ffa95b74ecc.png)
![2015-04-02_11 34 51](https://cloud.githubusercontent.com/assets/11773605/6967378/e1846610-d92c-11e4-882b-0a562f626a49.png)
![2015-04-02_11 34 52](https://cloud.githubusercontent.com/assets/11773605/6967379/e185a656-d92c-11e4-8cf9-64afb27d6663.png)
![2015-04-02_11 34 53](https://cloud.githubusercontent.com/assets/11773605/6967380/e185c6ae-d92c-11e4-8d0d-5098e3558442.png)

**Comment by ewized** [comment]
Thanks the issue has been dealt with. Thanks for reporting!
