### ISSUE TITLE
MrHondaxD Hacking

### ISSUE THREAD

**Issue by EtchedTree** [Year4000/Meta#15]
MrHondaxD using fastbow and fly to spawncamp.

![2015-04-02_17 17 06_2](https://cloud.githubusercontent.com/assets/11773605/6973941/83232ffe-d95c-11e4-9671-9626222b1afa.png)
![2015-04-02_17 17 06](https://cloud.githubusercontent.com/assets/11773605/6973944/87f0bc04-d95c-11e4-8cff-d6eec0b10d1b.png)
![2015-04-02_17 17 26_2](https://cloud.githubusercontent.com/assets/11773605/6973946/8bf85460-d95c-11e4-93da-3eda1c9150d9.png)

**Comment by kacgal** [comment]
He has been dealt with, thanks for reporting.
